FROM alpine:3.12

ADD https://dl.bintray.com/php-alpine/key/php-alpine.rsa.pub /etc/apk/keys/php-alpine.rsa.pub

RUN apk --update-cache add ca-certificates && \
    echo "https://dl.bintray.com/php-alpine/v3.12/php-7.4" >> /etc/apk/repositories
    
RUN apk --update-cache add \
      wget \
      curl \
      git \
      php7 \
      php7-curl \
      php7-intl \
      php7-json \
      php7-mbstring \
      php7-openssl \
      php7-pdo_mysql \
      php7-pdo_pgsql \
      php7-pdo_sqlite \
      php7-phar \
      php7-xml \
      php7-zlib \
      php7-session \
      apache2 \
      php7-apache2 && \
    rm /var/www/localhost/htdocs/*
    
RUN ln -s /usr/bin/php7 /usr/bin/php
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
RUN mkdir -p /run/apache2 && ln -sf /dev/stdout /var/log/apache2/access.log && ln -sf /dev/stderr /var/log/apache2/error.log
COPY httpd-foreground /usr/local/bin/

EXPOSE 80

CMD ["httpd-foreground"]
